// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: game_details.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGameDetails = `-- name: CreateGameDetails :one
INSERT INTO game_details 
(game_id, player_id, score)
VALUES ($1, $2, $3)
RETURNING id, game_id, player_id, score
`

type CreateGameDetailsParams struct {
	GameID   int64 `json:"gameId"`
	PlayerID int64 `json:"playerId"`
	Score    int32 `json:"score"`
}

// CreateGameDetails
//
//	INSERT INTO game_details
//	(game_id, player_id, score)
//	VALUES ($1, $2, $3)
//	RETURNING id, game_id, player_id, score
func (q *Queries) CreateGameDetails(ctx context.Context, arg CreateGameDetailsParams) (GameDetail, error) {
	row := q.db.QueryRow(ctx, createGameDetails, arg.GameID, arg.PlayerID, arg.Score)
	var i GameDetail
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.PlayerID,
		&i.Score,
	)
	return i, err
}

const deleteGameDetails = `-- name: DeleteGameDetails :exec
DELETE FROM game_details
WHERE id = $1
`

// DeleteGameDetails
//
//	DELETE FROM game_details
//	WHERE id = $1
func (q *Queries) DeleteGameDetails(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteGameDetails, id)
	return err
}

const deleteGameDetailsByGame = `-- name: DeleteGameDetailsByGame :exec
DELETE FROM game_details
WHERE game_id = $1
`

// DeleteGameDetailsByGame
//
//	DELETE FROM game_details
//	WHERE game_id = $1
func (q *Queries) DeleteGameDetailsByGame(ctx context.Context, gameID int64) error {
	_, err := q.db.Exec(ctx, deleteGameDetailsByGame, gameID)
	return err
}

const deleteGameDetailsByGameAndPlayer = `-- name: DeleteGameDetailsByGameAndPlayer :exec
DELETE FROM game_details
WHERE game_id = $1 AND player_id = $2
`

type DeleteGameDetailsByGameAndPlayerParams struct {
	GameID   int64 `json:"gameId"`
	PlayerID int64 `json:"playerId"`
}

// DeleteGameDetailsByGameAndPlayer
//
//	DELETE FROM game_details
//	WHERE game_id = $1 AND player_id = $2
func (q *Queries) DeleteGameDetailsByGameAndPlayer(ctx context.Context, arg DeleteGameDetailsByGameAndPlayerParams) error {
	_, err := q.db.Exec(ctx, deleteGameDetailsByGameAndPlayer, arg.GameID, arg.PlayerID)
	return err
}

const deleteGameDetailsByPlayer = `-- name: DeleteGameDetailsByPlayer :exec
DELETE FROM game_details
WHERE player_id = $1
`

// DeleteGameDetailsByPlayer
//
//	DELETE FROM game_details
//	WHERE player_id = $1
func (q *Queries) DeleteGameDetailsByPlayer(ctx context.Context, playerID int64) error {
	_, err := q.db.Exec(ctx, deleteGameDetailsByPlayer, playerID)
	return err
}

const deleteGameDetailsByTeam = `-- name: DeleteGameDetailsByTeam :exec
DELETE FROM game_details
WHERE player_id IN
  ( SELECT PLAYER_ID FROM players WHERE team_id = $1 )
`

// DeleteGameDetailsByTeam
//
//	DELETE FROM game_details
//	WHERE player_id IN
//	  ( SELECT PLAYER_ID FROM players WHERE team_id = $1 )
func (q *Queries) DeleteGameDetailsByTeam(ctx context.Context, teamID pgtype.Int8) error {
	_, err := q.db.Exec(ctx, deleteGameDetailsByTeam, teamID)
	return err
}

const listGameDetails = `-- name: ListGameDetails :many
SELECT id, game_id, player_id, score FROM game_details
`

// ListGameDetails
//
//	SELECT id, game_id, player_id, score FROM game_details
func (q *Queries) ListGameDetails(ctx context.Context) ([]GameDetail, error) {
	rows, err := q.db.Query(ctx, listGameDetails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GameDetail{}
	for rows.Next() {
		var i GameDetail
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.PlayerID,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGameDetailsByGameId = `-- name: ListGameDetailsByGameId :many
SELECT id, game_id, player_id, score from game_details
WHERE game_id = $1
`

// ListGameDetailsByGameId
//
//	SELECT id, game_id, player_id, score from game_details
//	WHERE game_id = $1
func (q *Queries) ListGameDetailsByGameId(ctx context.Context, gameID int64) ([]GameDetail, error) {
	rows, err := q.db.Query(ctx, listGameDetailsByGameId, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GameDetail{}
	for rows.Next() {
		var i GameDetail
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.PlayerID,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGameDetailsById = `-- name: ListGameDetailsById :many
SELECT id, game_id, player_id, score from game_details
where id = $1
`

// ListGameDetailsById
//
//	SELECT id, game_id, player_id, score from game_details
//	where id = $1
func (q *Queries) ListGameDetailsById(ctx context.Context, id int64) ([]GameDetail, error) {
	rows, err := q.db.Query(ctx, listGameDetailsById, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GameDetail{}
	for rows.Next() {
		var i GameDetail
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.PlayerID,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGameDetailsByTeamId = `-- name: ListGameDetailsByTeamId :many
SELECT id, game_id, player_id, score
FROM game_details
WHERE PLAYER_ID IN 
  (SELECT id FROM players WHERE team_id = $1)
`

// ListGameDetailsByTeamId
//
//	SELECT id, game_id, player_id, score
//	FROM game_details
//	WHERE PLAYER_ID IN
//	  (SELECT id FROM players WHERE team_id = $1)
func (q *Queries) ListGameDetailsByTeamId(ctx context.Context, teamID pgtype.Int8) ([]GameDetail, error) {
	rows, err := q.db.Query(ctx, listGameDetailsByTeamId, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GameDetail{}
	for rows.Next() {
		var i GameDetail
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.PlayerID,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGameDetailsVerbose = `-- name: ListGameDetailsVerbose :many
SELECT gd.player_id, gd.game_id, p.team_id, u.first_name, u.last_name, p.jersey_number, gd.score
FROM game_details as gd
INNER JOIN players as p ON gd.player_id = p.id
INNER JOIN users as u on u.id = p.user_id
order by game_id, team_id
`

type ListGameDetailsVerboseRow struct {
	PlayerID     int64       `json:"playerId"`
	GameID       int64       `json:"gameId"`
	TeamID       pgtype.Int8 `json:"teamId"`
	FirstName    string      `json:"firstName"`
	LastName     string      `json:"lastName"`
	JerseyNumber pgtype.Int4 `json:"jerseyNumber"`
	Score        int32       `json:"score"`
}

// ListGameDetailsVerbose
//
//	SELECT gd.player_id, gd.game_id, p.team_id, u.first_name, u.last_name, p.jersey_number, gd.score
//	FROM game_details as gd
//	INNER JOIN players as p ON gd.player_id = p.id
//	INNER JOIN users as u on u.id = p.user_id
//	order by game_id, team_id
func (q *Queries) ListGameDetailsVerbose(ctx context.Context) ([]ListGameDetailsVerboseRow, error) {
	rows, err := q.db.Query(ctx, listGameDetailsVerbose)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGameDetailsVerboseRow{}
	for rows.Next() {
		var i ListGameDetailsVerboseRow
		if err := rows.Scan(
			&i.PlayerID,
			&i.GameID,
			&i.TeamID,
			&i.FirstName,
			&i.LastName,
			&i.JerseyNumber,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGameDetailsScore = `-- name: UpdateGameDetailsScore :exec
UPDATE game_details
SET score = $3
WHERE game_id = $1 AND player_id = $2
`

type UpdateGameDetailsScoreParams struct {
	GameID   int64 `json:"gameId"`
	PlayerID int64 `json:"playerId"`
	Score    int32 `json:"score"`
}

// UpdateGameDetailsScore
//
//	UPDATE game_details
//	SET score = $3
//	WHERE game_id = $1 AND player_id = $2
func (q *Queries) UpdateGameDetailsScore(ctx context.Context, arg UpdateGameDetailsScoreParams) error {
	_, err := q.db.Exec(ctx, updateGameDetailsScore, arg.GameID, arg.PlayerID, arg.Score)
	return err
}
