// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Game struct {
	ID         int64            `json:"id"`
	HomeTeamID int64            `json:"homeTeamId"`
	AwayTeamID int64            `json:"awayTeamId"`
	HomeScore  int32            `json:"homeScore"`
	AwayScore  int32            `json:"awayScore"`
	GameTime   pgtype.Timestamp `json:"gameTime"`
	CreatedAt  pgtype.Timestamp `json:"createdAt"`
	UpdatedAt  pgtype.Timestamp `json:"updatedAt"`
	Status     string           `json:"status"`
}

type GameDetail struct {
	ID       int64 `json:"id"`
	GameID   int64 `json:"gameId"`
	PlayerID int64 `json:"playerId"`
	Score    int32 `json:"score"`
}

type PasswordResetToken struct {
	ID        int64            `json:"id"`
	UserID    int64            `json:"userId"`
	Token     string           `json:"token"`
	ExpiresAt pgtype.Timestamp `json:"expiresAt"`
	Used      bool             `json:"used"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
}

type Payment struct {
	ID            int64            `json:"id"`
	PlayerID      int64            `json:"playerId"`
	TransactionID string           `json:"transactionId"`
	Amount        int32            `json:"amount"`
	Status        string           `json:"status"`
	PaymentDate   pgtype.Timestamp `json:"paymentDate"`
}

type Player struct {
	ID           int64            `json:"id"`
	UserID       int64            `json:"userId"`
	TeamID       pgtype.Int8      `json:"teamId"`
	FeeRemainder int32            `json:"feeRemainder"`
	JerseyNumber pgtype.Int4      `json:"jerseyNumber"`
	CreatedAt    pgtype.Timestamp `json:"createdAt"`
	UpdatedAt    pgtype.Timestamp `json:"updatedAt"`
}

type Team struct {
	ID        int64            `json:"id"`
	Name      string           `json:"name"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
	UpdatedAt pgtype.Timestamp `json:"updatedAt"`
}

type User struct {
	ID           int64            `json:"id"`
	Email        string           `json:"email"`
	PhoneNumber  string           `json:"phoneNumber"`
	PasswordHash string           `json:"passwordHash"`
	FirstName    string           `json:"firstName"`
	LastName     string           `json:"lastName"`
	Role         string           `json:"role"`
	CreatedAt    pgtype.Timestamp `json:"createdAt"`
	UpdatedAt    pgtype.Timestamp `json:"updatedAt"`
}
