// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: password_reset.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one
INSERT INTO password_reset_tokens (user_id, token, expires_at)
VALUES ($1, $2, $3)
RETURNING id, token, expires_at
`

type CreatePasswordResetTokenParams struct {
	UserID    int64            `json:"userId"`
	Token     string           `json:"token"`
	ExpiresAt pgtype.Timestamp `json:"expiresAt"`
}

type CreatePasswordResetTokenRow struct {
	ID        int64            `json:"id"`
	Token     string           `json:"token"`
	ExpiresAt pgtype.Timestamp `json:"expiresAt"`
}

// CreatePasswordResetToken
//
//	INSERT INTO password_reset_tokens (user_id, token, expires_at)
//	VALUES ($1, $2, $3)
//	RETURNING id, token, expires_at
func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (CreatePasswordResetTokenRow, error) {
	row := q.db.QueryRow(ctx, createPasswordResetToken, arg.UserID, arg.Token, arg.ExpiresAt)
	var i CreatePasswordResetTokenRow
	err := row.Scan(&i.ID, &i.Token, &i.ExpiresAt)
	return i, err
}

const deleteExpiredPasswordResetTokens = `-- name: DeleteExpiredPasswordResetTokens :exec
DELETE FROM password_reset_tokens
WHERE expires_at < NOW() OR used = TRUE
`

// DeleteExpiredPasswordResetTokens
//
//	DELETE FROM password_reset_tokens
//	WHERE expires_at < NOW() OR used = TRUE
func (q *Queries) DeleteExpiredPasswordResetTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredPasswordResetTokens)
	return err
}

const getPasswordResetToken = `-- name: GetPasswordResetToken :one
SELECT id, user_id, token, expires_at, used, created_at
FROM password_reset_tokens
WHERE token = $1 AND used = FALSE AND expires_at > NOW()
`

// GetPasswordResetToken
//
//	SELECT id, user_id, token, expires_at, used, created_at
//	FROM password_reset_tokens
//	WHERE token = $1 AND used = FALSE AND expires_at > NOW()
func (q *Queries) GetPasswordResetToken(ctx context.Context, token string) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getPasswordResetToken, token)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const markPasswordResetTokenAsUsed = `-- name: MarkPasswordResetTokenAsUsed :exec
UPDATE password_reset_tokens
SET used = TRUE
WHERE token = $1
`

// MarkPasswordResetTokenAsUsed
//
//	UPDATE password_reset_tokens
//	SET used = TRUE
//	WHERE token = $1
func (q *Queries) MarkPasswordResetTokenAsUsed(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, markPasswordResetTokenAsUsed, token)
	return err
}
