// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, phone_number, password_hash, first_name, last_name, role)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PhoneNumber  string `json:"phoneNumber"`
	PasswordHash string `json:"passwordHash"`
	FirstName    string `json:"firstName"`
	LastName     string `json:"lastName"`
	Role         string `json:"role"`
}

// CreateUser
//
//	INSERT INTO users (email, phone_number, password_hash, first_name, last_name, role)
//	VALUES ($1, $2, $3, $4, $5, $6)
//	RETURNING id
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PhoneNumber,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
		arg.Role,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
where id = $1
`

// DeleteUser
//
//	DELETE FROM users
//	where id = $1
func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, phone_number, first_name, last_name, role, created_at, updated_at
FROM users WHERE email = $1
`

type GetUserByEmailRow struct {
	ID          int64            `json:"id"`
	Email       string           `json:"email"`
	PhoneNumber string           `json:"phoneNumber"`
	FirstName   string           `json:"firstName"`
	LastName    string           `json:"lastName"`
	Role        string           `json:"role"`
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
	UpdatedAt   pgtype.Timestamp `json:"updatedAt"`
}

// GetUserByEmail
//
//	SELECT id, email, phone_number, first_name, last_name, role, created_at, updated_at
//	FROM users WHERE email = $1
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.FirstName,
		&i.LastName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmailWithPassword = `-- name: GetUserByEmailWithPassword :one
SELECT id, email, phone_number, password_hash, first_name, last_name, role, created_at, updated_at
FROM users WHERE email = $1
`

// GetUserByEmailWithPassword
//
//	SELECT id, email, phone_number, password_hash, first_name, last_name, role, created_at, updated_at
//	FROM users WHERE email = $1
func (q *Queries) GetUserByEmailWithPassword(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmailWithPassword, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, email, phone_number, first_name, last_name, role, created_at, updated_at
FROM users WHERE id = $1
`

type GetUserByIdRow struct {
	ID          int64            `json:"id"`
	Email       string           `json:"email"`
	PhoneNumber string           `json:"phoneNumber"`
	FirstName   string           `json:"firstName"`
	LastName    string           `json:"lastName"`
	Role        string           `json:"role"`
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
	UpdatedAt   pgtype.Timestamp `json:"updatedAt"`
}

// GetUserById
//
//	SELECT id, email, phone_number, first_name, last_name, role, created_at, updated_at
//	FROM users WHERE id = $1
func (q *Queries) GetUserById(ctx context.Context, id int64) (GetUserByIdRow, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i GetUserByIdRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.FirstName,
		&i.LastName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, phone_number, first_name, last_name, role, created_at, updated_at
FROM users
order by id
`

type ListUsersRow struct {
	ID          int64            `json:"id"`
	Email       string           `json:"email"`
	PhoneNumber string           `json:"phoneNumber"`
	FirstName   string           `json:"firstName"`
	LastName    string           `json:"lastName"`
	Role        string           `json:"role"`
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
	UpdatedAt   pgtype.Timestamp `json:"updatedAt"`
}

// ListUsers
//
//	SELECT id, email, phone_number, first_name, last_name, role, created_at, updated_at
//	FROM users
//	order by id
func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PhoneNumber,
			&i.FirstName,
			&i.LastName,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET email = $1, phone_number = $2, first_name = $3, last_name = $4, role = $5, updated_at = $6
WHERE id = $7
`

type UpdateUserParams struct {
	Email       string           `json:"email"`
	PhoneNumber string           `json:"phoneNumber"`
	FirstName   string           `json:"firstName"`
	LastName    string           `json:"lastName"`
	Role        string           `json:"role"`
	UpdatedAt   pgtype.Timestamp `json:"updatedAt"`
	ID          int64            `json:"id"`
}

// UpdateUser
//
//	UPDATE users
//	SET email = $1, phone_number = $2, first_name = $3, last_name = $4, role = $5, updated_at = $6
//	WHERE id = $7
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.Email,
		arg.PhoneNumber,
		arg.FirstName,
		arg.LastName,
		arg.Role,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateUserEmail = `-- name: UpdateUserEmail :exec
UPDATE users
set email = $1
where id = $2
`

type UpdateUserEmailParams struct {
	Email string `json:"email"`
	ID    int64  `json:"id"`
}

// UpdateUserEmail
//
//	UPDATE users
//	set email = $1
//	where id = $2
func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error {
	_, err := q.db.Exec(ctx, updateUserEmail, arg.Email, arg.ID)
	return err
}

const updateUserName = `-- name: UpdateUserName :exec
UPDATE users
set first_name = $1, last_name = $2
WHERE id = $3
`

type UpdateUserNameParams struct {
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	ID        int64  `json:"id"`
}

// UpdateUserName
//
//	UPDATE users
//	set first_name = $1, last_name = $2
//	WHERE id = $3
func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) error {
	_, err := q.db.Exec(ctx, updateUserName, arg.FirstName, arg.LastName, arg.ID)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $1, updated_at = $2
WHERE id = $3
`

type UpdateUserPasswordParams struct {
	PasswordHash string           `json:"passwordHash"`
	UpdatedAt    pgtype.Timestamp `json:"updatedAt"`
	ID           int64            `json:"id"`
}

// UpdateUserPassword
//
//	UPDATE users
//	SET password_hash = $1, updated_at = $2
//	WHERE id = $3
func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.PasswordHash, arg.UpdatedAt, arg.ID)
	return err
}

const updateUserPhoneNumber = `-- name: UpdateUserPhoneNumber :exec
UPDATE users
set phone_number = $1
WHERE id = $2
`

type UpdateUserPhoneNumberParams struct {
	PhoneNumber string `json:"phoneNumber"`
	ID          int64  `json:"id"`
}

// UpdateUserPhoneNumber
//
//	UPDATE users
//	set phone_number = $1
//	WHERE id = $2
func (q *Queries) UpdateUserPhoneNumber(ctx context.Context, arg UpdateUserPhoneNumberParams) error {
	_, err := q.db.Exec(ctx, updateUserPhoneNumber, arg.PhoneNumber, arg.ID)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE users
set role = $1
WHERE id = $2
`

type UpdateUserRoleParams struct {
	Role string `json:"role"`
	ID   int64  `json:"id"`
}

// UpdateUserRole
//
//	UPDATE users
//	set role = $1
//	WHERE id = $2
func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.Exec(ctx, updateUserRole, arg.Role, arg.ID)
	return err
}
