// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Game struct {
	ID         int64            `json:"id"`
	HomeTeamID int64            `json:"homeTeamId"`
	AwayTeamID int64            `json:"awayTeamId"`
	GameTime   pgtype.Timestamp `json:"gameTime"`
	CreatedAt  pgtype.Timestamp `json:"createdAt"`
	UpdatedAt  pgtype.Timestamp `json:"updatedAt"`
}

type GameResult struct {
	ID            int64            `json:"id"`
	GameID        int64            `json:"gameId"`
	HomeScore     int32            `json:"homeScore"`
	AwayScore     int32            `json:"awayScore"`
	WinningTeamID pgtype.Int8      `json:"winningTeamId"`
	RecordedAt    pgtype.Timestamp `json:"recordedAt"`
}

type Payment struct {
	ID          int64            `json:"id"`
	PlayerID    int64            `json:"playerId"`
	StripeID    string           `json:"stripeId"`
	Amount      pgtype.Numeric   `json:"amount"`
	Status      string           `json:"status"`
	PaymentDate pgtype.Timestamp `json:"paymentDate"`
}

type Player struct {
	ID                 int64            `json:"id"`
	UserID             int64            `json:"userId"`
	TeamID             pgtype.Int8      `json:"teamId"`
	RegistrationFeeDue pgtype.Numeric   `json:"registrationFeeDue"`
	IsFullyRegistered  bool             `json:"isFullyRegistered"`
	IsActive           bool             `json:"isActive"`
	JerseyNumber       pgtype.Int4      `json:"jerseyNumber"`
	CreatedAt          pgtype.Timestamp `json:"createdAt"`
	UpdatedAt          pgtype.Timestamp `json:"updatedAt"`
}

type Team struct {
	ID            int64            `json:"id"`
	Name          string           `json:"name"`
	Wins          int32            `json:"wins"`
	Losses        int32            `json:"losses"`
	Draws         int32            `json:"draws"`
	PointsFor     int32            `json:"pointsFor"`
	PointsAgainst int32            `json:"pointsAgainst"`
	CreatedAt     pgtype.Timestamp `json:"createdAt"`
	UpdatedAt     pgtype.Timestamp `json:"updatedAt"`
}

type User struct {
	ID           int64            `json:"id"`
	Email        string           `json:"email"`
	PhoneNumber  string           `json:"phoneNumber"`
	PasswordHash string           `json:"passwordHash"`
	FirstName    string           `json:"firstName"`
	LastName     string           `json:"lastName"`
	Role         string           `json:"role"`
	CreatedAt    pgtype.Timestamp `json:"createdAt"`
	UpdatedAt    pgtype.Timestamp `json:"updatedAt"`
}
